name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs in the next 24 hours. Thank you
  for your contributions.'
          days-before-stale: 60
          days-before-close: 1
